FredricLaestander/u09

apps/backend/package.json
apps/backend/vercel.json
bun.lock

chore: add vercel.json

---

apps/backend/api/index.ts
apps/backend/api/routes.ts
apps/backend/yaak/yaak.fl_Rw5LdepaS5.yaml
apps/backend/yaak/yaak.fl_T2ct9HejfL.yaml
apps/backend/yaak/yaak.fl_Xz2CTzHsmm.yaml
apps/backend/yaak/yaak.rq_2wRG3ZVQmN.yaml
apps/backend/yaak/yaak.rq_HNh4n4F8Cz.yaml
apps/backend/yaak/yaak.rq_WhnAEA8YoJ.yaml
apps/backend/yaak/yaak.rq_auYS7Zqz55.yaml
apps/backend/yaak/yaak.rq_hucXkhdwGE.yaml
apps/backend/yaak/yaak.rq_iaPKfTZFBn.yaml
apps/backend/yaak/yaak.rq_q4W58km2FJ.yaml
apps/backend/yaak/yaak.wk_eovdddZRuv.yaml

closes #21
- set up routers and connect them to the app
- set up yaak synced workspace

feat: set up routes

---

.github/workflows/format.yml

closes #16 
- create a workflow that runs on pull requests and will fail if there are formatting issues

ci: create format workflow

---

.github/workflows/lint.yml

closes #15 
Created a lint pipeline

Feat: create lint pipeline

---

apps/backend/package.json
apps/backend/tsup.config.ts
apps/backend/vercel.json
bun.lock

add build script and move to render

fix: add build script

---

apps/backend/lib/error.ts
apps/backend/package.json
bun.lock

closes #69 
- create different types of errors for clarity and predictability
- `HandlerError` - general errors
- `NotFoundError` - when a resource cannot be found
- `ValidationError` - when data doesn't match the expected format
- `AuthError` - when something goes wrong with the authentication
- create `handleError` that handles errors respectively based on the type of error
- expected errors are sent back to the client with a message and a status code
- unexpected errors are logged to the console and a generic message is sent back to the client to avoid data leakage

feat: error handler

---

apps/frontend/package.json
apps/frontend/src/utils/classname.ts
bun.lock

- create a `cn` function that makes conditionally merging tailwind classes more predictable
read more about the function here: https://www.reddit.com/r/tailwindcss/comments/1egbuvx/the_buzz_around_cn_function_and_why_do_we_use_it/

feat: classnames helper function

---

apps/frontend/src/components/BackButton.tsx

closes #57 
- create button that navigates to the previous url
https://github.com/user-attachments/assets/017aba0a-20cc-451d-bfc4-884811036e03

feat: back button

---

.github/workflows/format.yml
apps/backend/package.json
package.json
turbo.json

change the format command in the ci so that it actually picks up our ignore
follow up on #94

ci: fix format command

---

apps/frontend/package.json
apps/frontend/src/components/Toaster.tsx
apps/frontend/src/layout.tsx
apps/frontend/src/router.tsx
bun.lock

closes #51 
- create a `Toaster` built on top of the [radix-ui toast](https://www.radix-ui.com/primitives/docs/components/toast)
- create a context that keeps track of the toasts
- create a hook that returns functions (just `toast.error` atm) for showing a toast
- create a `Layout` component and wrap all of the routes in it
```ts
const toast = useToast()
return <Button onClick={() => toast.error('an error happened')}>toast</Button>
```
https://github.com/user-attachments/assets/e32ea5b8-460a-4739-a201-fb43ed42c1f2
_note:_ it would be nice to add some animations to this but i decided not to prioritize that!

feat: create `Toaster`

---

bun.lock
package.json

updated `turbo` to latest update ( ~~2.5.3~~ -> 2.5.4)

chore: update turbo in root

---

apps/backend/controllers/auth.ts

just adds a message to follow our response structure of always sending some sort of message

refactor: respond with message when issuing tokens

---

apps/frontend/index.html
apps/frontend/src/pages/MainMenu.tsx

closes #59 
- render logo art
- render links to game and profile
- update base styling to add basic layout

feat: main menu

---

apps/backend/api/routes.ts
apps/backend/controllers/auth.ts
apps/backend/yaak/yaak.rq_hucXkhdwGE.yaml

closes #23 
- create log out handler
- deletes the refresh token from the database if there is one
- clears the cookies

feat: log out handler

---

apps/frontend/package.json
apps/frontend/src/components/modals/Modals.tsx
apps/frontend/src/components/modals/Wrapper.tsx
apps/frontend/src/hooks/useModal.tsx
apps/frontend/src/layout.tsx
bun.lock

closes #112 
- create `useModal` that uses a context to keep track of all modals in the app
- it keeps track of the type of modal
- provides functions to check if a certain modal is open, open a modal from anywhere in the app and close a modal
- has `ModalProvider` that has been added in `layout.tsx`
- create `Modals` which is currently empty, this is where all modals will be rendered
- create `Wrapper` that has the base styling, keeps track of the open state and handles closing
- uses `@radix-ui/react-dialog`
add a new `ModalType` in `useModal.tsx`
```tsx
export type ModalType = 'game-menu' | 'game-over' | 'test'
```
create a new modal using the `Wrapper`. remember to provide a `Primitive.Title` for accessibility
```tsx
import * as Primitive from '@radix-ui/react-dialog'
import { Wrapper …
```

feat: create `useModal`

---

apps/backend/controllers/auth.ts
apps/backend/controllers/user.ts
apps/backend/prisma/schema.prisma
apps/frontend/src/types/data.ts

- add `givenName` from google since we need it for the personalize account page
- update `select` in `getMe`
- update types

feat: add `givenName` to users

---

apps/frontend/src/hooks/useAuth.ts
apps/frontend/src/lib/clients/backend.ts
apps/frontend/src/lib/requests.ts

- create `useAuth` hook for fetching the current user
- returns `null` if there is no logged in user and returns `User` data if there is one
- has `isLoading` to be able to wait and see if there is a user before acting
- create `getMe` function that communicates with the backend
- update `backend` axios client with `withCredentials: true` to always include cookies in the requests

feat: create `useAuth`

---

apps/frontend/index.html
apps/frontend/package.json
apps/frontend/src/lib/requests.ts
apps/frontend/src/pages/PersonalizeAccount.tsx
bun.lock

closes #53 
- create `updateUsername`
- add content and functionality to `PersonalizeAccountPage`

feat: create personalize account page

---

apps/frontend/src/components/Header.tsx
apps/frontend/src/pages/Game.tsx
apps/frontend/src/pages/Landing.tsx
apps/frontend/src/pages/Profile.tsx

- create `Header` with layout styling for the headers in the app
- switch out the existing headers

refactor: create `Header`

---

apps/backend/controllers/user.ts

- add an error for "username taken" in `user.update`

refactor: username taken error

---

apps/frontend/src/components/CardFront.tsx
apps/frontend/src/hooks/useGame.ts
apps/frontend/src/lib/requests.ts
apps/frontend/src/pages/Game.tsx
apps/frontend/src/types/data.ts
apps/frontend/src/types/utils.ts

closes #62 
- create `useGame`
- create `drawInitialCards`
- replace the static cards with real data

feat: render initial draw

---

apps/frontend/src/lib/requests.ts
apps/frontend/src/lib/score.ts
apps/frontend/src/types/utils.ts

- create a function to calculate the score of a hand
- use it in `drawInitialCards` and assign a score to each hand

feat: calculate score

---

apps/frontend/src/pages/Game.tsx

close #138 
- render the users streak if it is 2 or more

feat: display streak

---

apps/frontend/src/hooks/useGame.tsx
apps/frontend/src/pages/Game.tsx

closes #63 
- create `stand` in `useGame`
- use it `onClick` on stand button
- reveal the dealers hidden card
- create function to determine the next action based on the dealer score

feat: stand

---

apps/frontend/src/hooks/useGame.tsx

closes #64 
- create `decideWinner`
- used in `runDealerAction`
- create `getHighestValidScore`

feat: decide winner

---

apps/frontend/src/hooks/useAuth.tsx

- use `useQuery` to fetch the user in `useAuth`

refactor: `useQuery` in `useAuth`

---

apps/frontend/src/hooks/useGame.tsx
apps/frontend/src/lib/requests.ts
apps/frontend/src/pages/Game.tsx
apps/frontend/src/types/data.ts

closes #67 
made draw functionality
* Draws 1 card
* updates deck count
made hit functionallity
* uses `draw()` and assigns the card to the player
* updates hand count to represent the card value in hand
made a formatdeck function
* used for some api validation

feat: `draw` & `hit`

---

apps/frontend/src/pages/Game.tsx

split `GamePage` into `GameHeader`, `DealerHand`, `PlayerHand` & `Actions`
when the game grows and becomes more complex this component is going to get bigger and bigger. separating it will make the file easier to read

refactor: split `GamePage` into smaller component

---

apps/frontend/src/hooks/useGame.tsx

closes #166 
automatically end the players turn if the hand bust

feat: player bust

---

apps/backend/prisma/schema.prisma
apps/frontend/src/lib/requests.ts
apps/frontend/src/pages/EditProfile.tsx
apps/frontend/src/providers/QueryClientProvider.tsx

closes #58 
made edit-profile page
* Rendered edit-profile page
* Function to update username similiar to `personalize-user` page
* Created deleteUser function
* exported queryClient to use in delete function

feat: `edit-profile` page

---

apps/frontend/src/lib/score.ts
apps/frontend/src/types/utils.ts

- create `hasBlackjack`
- add `cardLength` to `score`
- if both has blackjack, there is a tie
- if player has blackjack, it wins (even if the dealer also has 21 but with more than 2 cards)

fix: winner if blackjack

---

apps/frontend/package.json
apps/frontend/src/components/Loading.tsx
apps/frontend/src/hooks/useAuth.tsx
bun.lock

- install `motion`
- create a loading screen
- use in in `AuthProvider`
https://github.com/user-attachments/assets/8981a37c-b033-4c25-aa76-ae56115bfa05
https://examples.motion.dev/react/loading-jumping-dots

feat: create loading screen

---

apps/backend/lib/error.ts

check for errors to fix production

---

apps/backend/lib/error.ts

Reverts FredricLaestander/u09#180
we found the issue

Revert "check for errors to fix production"

---

apps/frontend/src/hooks/useGame.tsx

fix: don't refetch on window focus
